import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { expect, test } from "vitest";
import { CoffeeJSONView } from "../src/CoffeeJSONView";

const bag = JSON.parse(
  readFileSync(
    new URL("../../../fixtures/valid/bag-to-brew.json", import.meta.url),
    "utf8",
  ),
);

test("bag-to-brew: bean card first, then all recipes, recommended badge present", () => {
  const html = renderToStaticMarkup(<CoffeeJSONView doc={bag} />);
  expect(html).toContain('class="cj-view"');
  expect(html.indexOf("cj-bean-card")).toBeGreaterThan(-1);
  expect(html.indexOf("cj-bean-card")).toBeLessThan(
    html.indexOf("cj-recipe-card"),
  );
  expect((html.match(/cj-recipe-card/g) ?? []).length).toBe(bag.recipes.length);
  expect(html).toContain("Recommended");
  expect(html).toContain("Las Brisas");
});

const withGenerator = (generator: unknown) => ({
  coffeejson: "1.0",
  generator,
  recipes: [
    {
      title: "t",
      coffee: { value: 15, unit: "gram" },
      water: { value: 250, unit: "gram" },
    },
  ],
});

test("generator renders once for the document, after the cards", () => {
  const html = renderToStaticMarkup(
    <CoffeeJSONView
      doc={withGenerator({
        name: "ExampleBrewApp",
        version: "2.3.0",
        url: "https://example.com/brewapp",
      })}
    />,
  );
  expect((html.match(/cj-generator/g) ?? []).length).toBe(1);
  expect(html).toContain("Generated by");
  expect(html).toContain("ExampleBrewApp 2.3.0");
  expect(html).toContain('href="https://example.com/brewapp"');
  expect(html.indexOf("cj-recipe-card")).toBeLessThan(
    html.indexOf("cj-generator"),
  );
});

test("generator renders once for a MULTI-recipe document, not once per recipe", () => {
  // The per-item repetition that putting this on the recipe would produce.
  const doc = {
    coffeejson: "1.0",
    generator: { name: "ExampleBrewApp" },
    recipes: [
      {
        title: "a",
        coffee: { value: 15, unit: "gram" },
        water: { value: 250, unit: "gram" },
      },
      {
        title: "b",
        coffee: { value: 18, unit: "gram" },
        water: { value: 300, unit: "gram" },
      },
      {
        title: "c",
        coffee: { value: 20, unit: "gram" },
        water: { value: 320, unit: "gram" },
      },
    ],
  };
  const html = renderToStaticMarkup(<CoffeeJSONView doc={doc} />);
  expect((html.match(/cj-recipe-card/g) ?? []).length).toBe(3);
  expect((html.match(/cj-generator/g) ?? []).length).toBe(1);
});

test("a bean-only document can carry a generator — it has no recipe to hang it on", () => {
  const html = renderToStaticMarkup(
    <CoffeeJSONView
      doc={{
        coffeejson: "1.0",
        generator: { name: "ExampleBrewApp" },
        beans: [{ name: "Monarch", roaster: { name: "Onyx Coffee Lab" } }],
      }}
    />,
  );
  expect(html).toContain("cj-bean-card");
  expect(html).toContain("cj-generator");
});

test("unsafe generator URL renders as text, never an href", () => {
  const html = renderToStaticMarkup(
    <CoffeeJSONView
      doc={withGenerator({ name: "Evil", url: "javascript:alert(1)" })}
    />,
  );
  expect(html).toContain("cj-generator");
  expect(html).not.toContain("href=");
  expect(html).not.toContain("javascript:");
});

test("no generator, or a nameless one, renders no line at all", () => {
  for (const g of [
    undefined,
    {},
    { version: "1.0" },
    { name: "" },
    "ExampleBrewApp",
  ]) {
    expect(
      renderToStaticMarkup(<CoffeeJSONView doc={withGenerator(g)} />),
    ).not.toContain("cj-generator");
  }
});

test("show.generator gates the line", () => {
  const html = renderToStaticMarkup(
    <CoffeeJSONView
      doc={withGenerator({ name: "ExampleBrewApp" })}
      config={{ show: { generator: false } }}
    />,
  );
  expect(html).not.toContain("cj-generator");
});

test("empty/garbage docs render the fallback (default: nothing)", () => {
  expect(renderToStaticMarkup(<CoffeeJSONView doc={42} />)).toBe("");
  expect(
    renderToStaticMarkup(<CoffeeJSONView doc={{ coffeejson: "1.0" }} />),
  ).toBe("");
  const html = renderToStaticMarkup(
    <CoffeeJSONView
      doc={null}
      renderEmpty={() => <p className="nothing">no recipe here</p>}
    />,
  );
  expect(html).toBe('<p class="nothing">no recipe here</p>');
});
