import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { payloadFromLocation } from "@coffeejson/core";
import { describe, expect, it } from "vitest";
import { SHARE_PATH, SITE_URL } from "../tools/gen.mjs";

const site = fileURLToPath(new URL("..", import.meta.url));
const read = (p: string) => readFileSync(join(site, p), "utf8");

// The site emits the trailing-slash form so nothing it produces depends
// on a Pages 301 preserving the query — while still accepting the bare form,
// which is what the transport spec and the frozen consumer transport emit.
describe("share-link path normalization", () => {
  it("emits the trailing-slash form", () => {
    expect(SHARE_PATH).toBe("/r/?d=");
  });

  it("parses both shapes identically — inbound bare /r?d= must keep working", () => {
    const search = "?d=eyJhIjoxfQ";
    expect(payloadFromLocation(search)).toBe("eyJhIjoxfQ");
    // The parser reads location.search only; the path never enters into it, so
    // /r?d=, /r/?d= and any future prefix all resolve the same payload.
    expect(payloadFromLocation(new URL(`${SITE_URL}/r?d=eyJhIjoxfQ`).search)).toBe("eyJhIjoxfQ");
    expect(payloadFromLocation(new URL(`${SITE_URL}/r/?d=eyJhIjoxfQ`).search)).toBe("eyJhIjoxfQ");
  });

  // The transport rejects a fragment binding, and nothing emits one. This pins
  // that the site reads the query and only the query — the fallback cannot
  // quietly come back.
  it("does not read a #fragment payload", () => {
    expect(payloadFromLocation("")).toBeNull();
  });

  it("every generated share link in the site source uses the normalized form", () => {
    const sources = [
      "src/lib/save.ts",
      "src/pages/recipes.ts",
      "src/pages/landing.ts",
      "src/pages/generate.tsx",
    ];
    for (const f of sources) {
      // Template-literal link construction only — prose and placeholders that
      // illustrate the spec's `…/r?d=…` transport form are deliberately exempt.
      const bare = [...read(f).matchAll(/`[^`]*\/r\?d=\$\{/g)];
      expect(bare.map(() => f), `${f} builds a bare /r?d= link`).toEqual([]);
    }
  });

  it("the demo QR encodes the normalized URL", () => {
    const svg = read("public/demo/tetsu-kasuya-4-6.svg");
    expect(svg.length).toBeGreaterThan(0); // generated by `pnpm gen`
  });
});
