import type { DecodeError } from "./codec.js";
import type {
  BrewMethod,
  FilterMaterial,
  GrindSize,
  Process,
  RecommendedProducerRole,
  RoastLevel,
  StepKind,
} from "./vocabularies.js";

export interface LabelSet {
  facts: {
    dose: string;
    coffee: string;
    water: string;
    ratio: string;
    waterTemp: string;
    grind: string;
    pressure: string;
    preinfusion: string;
    basket: string;
    filter: string;
    shotTime: string;
    finish: string;
    roaster: string;
    origin: string;
    process: string;
    varietals: string;
    roast: string;
    roasterNotes: string;
    additions: string;
    /** Caption for the Agtron roast-color reading, e.g. "Agtron 62". */
    agtron: string;
    /** Caption for an origin item's harvest period, e.g. "Harvest Oct–Dec 2024". */
    harvest: string;
  };
  /** Prefix for the document's `generator` — "Generated by ExampleBrewApp 2.3.0".
   *  Document-level, so it sits outside `facts` (which labels recipe rows). */
  generatedBy: string;
  additionKinds: { ice: string; other: string };
  /** Filter materials — a closed vocabulary; an unrecognized value reads as `other`. */
  filterMaterials: Record<FilterMaterial, string>;
  /**
   * The brew-timer surface, not card rows. `next` and `reset` are full phrases
   * ("Start over") because `<BrewControls>` uses them as accessible names of
   * icon-only buttons; `step`, `pour`, `total` and `pourTo` are prefixes the
   * component completes ("<pourTo> 250 g").
   */
  brew: {
    pause: string;
    resume: string;
    next: string;
    reset: string;
    nextPourIn: string;
    finishIn: string;
    now: string;
    complete: string;
    getReady: string;
    step: string;
    pour: string;
    total: string;
    pourTo: string;
    pourCounter: string;
    done: string;
    /** Unit suffix for a duration stated in seconds, e.g. "5 s". */
    seconds: string;
  };
  /**
   * Every closed vocabulary a renderer prints, keyed by its union so a token the
   * format grows is a compile error here rather than a slug on screen. A
   * component never spells a token: it reads one of these. The spec's two
   * fallbacks fall out of the tables themselves — see `vocabularyLabel`.
   */
  methods: Record<BrewMethod, string>;
  processes: Record<Process, string>;
  stepKinds: Record<StepKind, string>;
  roastLevels: Record<RoastLevel, string>;
  grindSizes: Record<GrindSize, string>;
  /** The recommended producer roles. The registry is open, so the lookup falls
   *  back to the token — see `roleLabel`, not `vocabularyLabel`. */
  producerRoles: Record<RecommendedProducerRole, string>;
  /**
   * One sentence per decode reason, keyed by the codec's own vocabulary so a
   * reason the format grows is a compile error rather than a blank cell. A
   * consumer's own post-decode failures are its own words, not these.
   */
  decodeErrors: Record<DecodeError["kind"], string>;
  beanFallback: string;
  badge: string;
}

export const defaultLabels: LabelSet = {
  facts: {
    dose: "Dose",
    coffee: "Coffee",
    water: "Water",
    ratio: "Ratio",
    waterTemp: "Water temp",
    grind: "Grind",
    pressure: "Pressure",
    preinfusion: "Pre-infusion",
    basket: "Basket",
    filter: "Filter",
    shotTime: "Shot time",
    finish: "Finish",
    roaster: "Roaster",
    origin: "Origin",
    process: "Process",
    varietals: "Varietals",
    roast: "Roast",
    roasterNotes: "Roaster's notes",
    additions: "Additions",
    agtron: "Agtron",
    harvest: "Harvest",
  },
  generatedBy: "Generated by",
  additionKinds: { ice: "Ice", other: "Other" },
  filterMaterials: {
    paper: "Paper",
    metal: "Metal",
    cloth: "Cloth",
    other: "Other",
  },
  brew: {
    pause: "Pause",
    resume: "Resume",
    next: "Done, next step",
    reset: "Start over",
    nextPourIn: "Next pour in",
    finishIn: "Finish in",
    now: "Now",
    complete: "Brew complete",
    getReady: "Get ready…",
    step: "Step",
    pour: "Pour",
    total: "Total",
    pourTo: "Pour to",
    // Capitalized in the string rather than by CSS because the pour counter's
    // class carries no rule in the default skin to apply `text-transform`.
    pourCounter: "POUR",
    done: "Done",
    seconds: "s",
  },
  // Null-proto: these slugs come off the wire, and a JSON-legal key like
  // "__proto__" would otherwise resolve through Object.prototype to a non-string.
  methods: Object.assign(Object.create(null) as Record<string, string>, {
    pour_over: "Pour-over",
    immersion: "Immersion",
    aeropress: "AeroPress",
    french_press: "French press",
    moka: "Moka pot",
    cold_brew: "Cold brew",
    siphon: "Siphon",
    cezve: "Cezve",
    drip: "Drip machine",
    capsule: "Capsule",
    espresso: "Espresso",
    other: "Other",
  }),
  processes: Object.assign(Object.create(null) as Record<string, string>, {
    washed: "Washed",
    natural: "Natural",
    pulped_natural: "Pulped natural",
    honey: "Honey",
    anaerobic: "Anaerobic",
    carbonic_maceration: "Carbonic maceration",
    wet_hulled: "Wet-hulled",
    other: "Other",
  }),
  // Imperatives, because a step kind tags an instruction: "[Close valve] shut
  // the switch". A card suppresses the `pour` tag — it is the kind a step means
  // when it states none, so tagging every one of them says nothing.
  stepKinds: Object.assign(Object.create(null) as Record<string, string>, {
    pour: "Pour",
    bloom: "Bloom",
    prep: "Prep",
    wait: "Wait",
    stir: "Stir",
    flip: "Flip",
    valve_open: "Open valve",
    valve_close: "Close valve",
    press: "Press",
    drawdown: "Drawdown",
    distribute: "Distribute",
    tamp: "Tamp",
    pull: "Pull",
    other: "Other",
  }),
  // The two ordered scales, and the two sets with no `other` to fall back to.
  // Hyphenation follows the retail scale the spec names (Light-Medium, …).
  roastLevels: Object.assign(Object.create(null) as Record<string, string>, {
    light: "Light",
    light_medium: "Light-medium",
    medium: "Medium",
    medium_dark: "Medium-dark",
    dark: "Dark",
    extra_dark: "Extra-dark",
  }),
  grindSizes: Object.assign(Object.create(null) as Record<string, string>, {
    extra_fine: "Extra-fine",
    fine: "Fine",
    medium_fine: "Medium-fine",
    medium: "Medium",
    medium_coarse: "Medium-coarse",
    coarse: "Coarse",
    extra_coarse: "Extra-coarse",
  }),
  producerRoles: Object.assign(Object.create(null) as Record<string, string>, {
    producer: "Producer",
    farm: "Farm",
    cooperative: "Cooperative",
    washing_station: "Washing station",
    mill: "Mill",
    exporter: "Exporter",
  }),
  // In decode order, so the table reads as the algorithm does.
  decodeErrors: {
    no_payload: "This link carries no document.",
    malformed_base64:
      "The payload is not valid base64url — the link was probably truncated in transit.",
    unrecognized_encoding:
      "The payload is not in a form this build reads — a share payload is JSON, compressed or not.",
    damaged_compression:
      "The payload is compressed but damaged — it was probably altered in transit.",
    too_large: "The payload is past the 8 KiB cap.",
    not_utf8: "The payload is not valid UTF-8 text.",
    not_json: "The payload decodes, but it is not JSON.",
    not_a_document: "The payload is JSON, but not a CoffeeJSON document.",
    unsupported_version:
      "This document states a CoffeeJSON version this build does not read. It is not being misread, only not shown.",
    empty_document:
      "This CoffeeJSON envelope carries nothing to show — no coffee and no recipe.",
    not_a_url: "That is not a link. A share is a URL carrying a payload.",
    not_http: "That link is not http(s), and nothing else is opened.",
  },
  beanFallback: "Coffee",
  badge: "Recommended",
};

export interface PartialLabels {
  facts?: Partial<LabelSet["facts"]>;
  generatedBy?: string;
  additionKinds?: Partial<LabelSet["additionKinds"]>;
  filterMaterials?: Partial<LabelSet["filterMaterials"]>;
  brew?: Partial<LabelSet["brew"]>;
  /** Open on purpose, unlike the defaults: a consumer must be able to localize a
   *  token this build does not know, exactly as it must not reject a document for
   *  carrying one. */
  methods?: Record<string, string>;
  processes?: Record<string, string>;
  stepKinds?: Record<string, string>;
  roastLevels?: Record<string, string>;
  grindSizes?: Record<string, string>;
  producerRoles?: Record<string, string>;
  decodeErrors?: Partial<LabelSet["decodeErrors"]>;
  beanFallback?: string;
  badge?: string;
}

// Prototype-less for the reason `defaultLabels` is.
const vocabulary = <T extends Record<string, string>>(
  base: T,
  overrides?: Record<string, string>,
): T => Object.assign(Object.create(null) as T, base, overrides);

// Deep-merge over the English defaults: `facts` key-by-key, a vocabulary by
// token, so an unnamed default survives either way.
export function mergeLabels(overrides?: PartialLabels): LabelSet {
  return {
    facts: { ...defaultLabels.facts, ...overrides?.facts },
    generatedBy: overrides?.generatedBy ?? defaultLabels.generatedBy,
    additionKinds: {
      ...defaultLabels.additionKinds,
      ...overrides?.additionKinds,
    },
    filterMaterials: {
      ...defaultLabels.filterMaterials,
      ...overrides?.filterMaterials,
    },
    brew: { ...defaultLabels.brew, ...overrides?.brew },
    methods: vocabulary(defaultLabels.methods, overrides?.methods),
    processes: vocabulary(defaultLabels.processes, overrides?.processes),
    stepKinds: vocabulary(defaultLabels.stepKinds, overrides?.stepKinds),
    roastLevels: vocabulary(defaultLabels.roastLevels, overrides?.roastLevels),
    grindSizes: vocabulary(defaultLabels.grindSizes, overrides?.grindSizes),
    producerRoles: vocabulary(
      defaultLabels.producerRoles,
      overrides?.producerRoles,
    ),
    decodeErrors: { ...defaultLabels.decodeErrors, ...overrides?.decodeErrors },
    beanFallback: overrides?.beanFallback ?? defaultLabels.beanFallback,
    badge: overrides?.badge ?? defaultLabels.badge,
  };
}
