import type { ComponentType } from "react";
import type { LabelSet, Measurement, NormalizedStep, PartialLabels, UnitSystem } from "@coffeejson/core";
import { convertMeasurement, fmtMeasurement, mergeLabels } from "@coffeejson/core";

/**
 * The addressable parts of the `cj-*` DOM contract. Status and variant modifiers
 * (`--current`, `--compact`, `--idle`…) are NOT parts — a component appends those
 * per render. The four fixed modifiers below have one meaning each, so each is.
 */
export type CjPart =
  | "view" | "card" | "recipeCard" | "beanCard" | "title" | "badge" | "subtitle"
  | "fact" | "factLabel" | "factValue" | "originItem"
  | "steps" | "step" | "stepActive" | "stepTime" | "stepBody" | "stepTarget"
  | "stepDelta" | "stepDeltaNone"
  | "generator" | "notes" | "description"
  | "brew" | "brewClock" | "brewControls" | "brewBtn" | "brewBtnPrimary" | "brewBtnGhost"
  | "timeline" | "timelineMarker"
  | "stepCard" | "stepCardHead" | "stepCardStep" | "stepCardTime" | "stepCardText"
  | "stepCardPour" | "stepCardTotal" | "stepCardLabel" | "stepCardMsg"
  | "countdown" | "countdownLabel" | "countdownValue" | "countdownPour"
  | "stepList" | "stepListRow" | "stepListIndex" | "stepListTime" | "stepListLabel"
  | "stepListDelta"
  | "pourCounter" | "pourCounterN";

/** Props a `components.Fact` override receives. `id` is the same field-id
 *  vocabulary as the `data-cj-fact` attribute (`dose`, `ratio`, `grind`, …). */
export interface FactViewProps {
  id: string;
  label: string;
  value: string;
}

export interface BadgeViewProps {
  label: string;
}

/**
 * Consumer-supplied replacements for leaf parts. An override owns its markup — the
 * default `cj-*` structure is *replaced*, not wrapped — and must be pure and
 * SSR-safe. The bean rows and the step-schedule row are not overridable.
 */
export interface CoffeeJSONComponents {
  /** Replaces a label/value fact row — every `<Fact>`-rendered row (all recipe
   *  facts + bean process/varietals/roast). */
  Fact?: ComponentType<FactViewProps>;
  /** Replaces the "Recommended" badge in a recipe title. */
  Badge?: ComponentType<BadgeViewProps>;
}

export interface CoffeeJSONConfig {
  /** Coarse whole-section gates. All default to `true`. `dose`/`ratio`/`waterTemp` always show. */
  show?: {
    bean?: boolean;
    steps?: boolean;
    grind?: boolean;
    /** The method·brewer subtitle + basket/brewer labels. */
    gear?: boolean;
    /** The document's "Generated by …" line. */
    generator?: boolean;
    espresso?: boolean;
  };
  /** Measurement unit system. Default `"as-authored"` (values render unchanged). */
  units?: UnitSystem;
  /** BCP-47 locale tag; drives `Intl.NumberFormat` for measurement/number digits. Default `"en"`. */
  locale?: string;
  /** Deep-merged over `@coffeejson/core`'s English `defaultLabels`. */
  labels?: PartialLabels;
  /** Additive class per frozen `cj-*` part — appended alongside the frozen class, never replacing it. */
  classNames?: Partial<Record<CjPart, string>>;
  /** Swap how individual leaf parts render — see {@link CoffeeJSONComponents}. */
  components?: CoffeeJSONComponents;
}

export interface ResolvedConfig {
  show: Required<NonNullable<CoffeeJSONConfig["show"]>>;
  units: UnitSystem;
  locale: string;
  labels: LabelSet;
  classNames: Partial<Record<CjPart, string>>;
  components: CoffeeJSONComponents;
}

const DEFAULT_SHOW: ResolvedConfig["show"] = {
  bean: true, steps: true, grind: true, gear: true, generator: true, espresso: true,
};

// Resolving is pure and every component calls it per render, so a WeakMap gives
// them one shared result to memoize on and holds nothing alive. Keyed on identity,
// not contents, so a fresh object literal per render misses and resolves again.
const RESOLVED = new WeakMap<CoffeeJSONConfig, ResolvedConfig>();

// No object to key on, so it resolves once and is shared — never mutated.
let resolvedDefault: ResolvedConfig | undefined;

// Fills every default, so no component special-cases a missing `config` prop.
export function resolveConfig(config?: CoffeeJSONConfig): ResolvedConfig {
  if (config === undefined) return (resolvedDefault ??= build(undefined));
  const hit = RESOLVED.get(config);
  if (hit) return hit;
  const built = build(config);
  RESOLVED.set(config, built);
  return built;
}

function build(config: CoffeeJSONConfig | undefined): ResolvedConfig {
  return {
    show: { ...DEFAULT_SHOW, ...config?.show },
    units: config?.units ?? "as-authored",
    locale: config?.locale ?? "en",
    labels: mergeLabels(config?.labels),
    classNames: config?.classNames ?? {},
    components: config?.components ?? {},
  };
}

const FROZEN_CLASS: Record<CjPart, string> = {
  view: "cj-view", card: "cj-card", recipeCard: "cj-recipe-card", beanCard: "cj-bean-card",
  title: "cj-title", badge: "cj-badge", subtitle: "cj-subtitle",
  fact: "cj-fact", factLabel: "cj-fact-label", factValue: "cj-fact-value", originItem: "cj-origin-item",
  steps: "cj-steps", step: "cj-step", stepActive: "cj-step--active",
  stepTime: "cj-step-time", stepBody: "cj-step-body", stepTarget: "cj-step-target",
  stepDelta: "cj-step-delta", stepDeltaNone: "cj-step-delta--none",
  generator: "cj-generator", notes: "cj-notes", description: "cj-description",
  brew: "cj-brew", brewClock: "cj-brew-clock", brewControls: "cj-brew-controls",
  brewBtn: "cj-brew-btn", brewBtnPrimary: "cj-brew-btn--primary", brewBtnGhost: "cj-brew-btn--ghost",
  timeline: "cj-timeline", timelineMarker: "cj-timeline-marker",
  stepCard: "cj-stepcard", stepCardHead: "cj-stepcard-head", stepCardStep: "cj-stepcard-step",
  stepCardTime: "cj-stepcard-time", stepCardText: "cj-stepcard-text",
  stepCardPour: "cj-stepcard-pour", stepCardTotal: "cj-stepcard-total",
  stepCardLabel: "cj-stepcard-label", stepCardMsg: "cj-stepcard-msg",
  countdown: "cj-countdown", countdownLabel: "cj-countdown-label",
  countdownValue: "cj-countdown-value", countdownPour: "cj-countdown-pour",
  stepList: "cj-steplist", stepListRow: "cj-steplist-row", stepListIndex: "cj-steplist-index",
  stepListTime: "cj-steplist-time", stepListLabel: "cj-steplist-label",
  stepListDelta: "cj-steplist-delta",
  pourCounter: "cj-pourcounter", pourCounterN: "cj-pourcounter-n",
};

// Never replaces the frozen class — `classNames` is purely additive.
export function cx(part: CjPart, rc: ResolvedConfig): string {
  const frozen = FROZEN_CLASS[part];
  const extra = rc.classNames[part];
  return extra ? `${frozen} ${extra}` : frozen;
}

// One per locale for the life of the module: construction costs ~17× a use, and a
// card formats ~14 measurements per render. A malformed tag ("en_US") throws a
// RangeError, so it degrades; a well-formed unknown one ("zz") passes through.
const NUMBER_FORMATS = new Map<string, Intl.NumberFormat>();
const FALLBACK_LOCALE = "en";

function numberFormat(locale: string): Intl.NumberFormat {
  const hit = NUMBER_FORMATS.get(locale);
  if (hit) return hit;
  let nf: Intl.NumberFormat;
  try {
    nf = new Intl.NumberFormat(locale, { maximumFractionDigits: 1, useGrouping: false });
  } catch {
    nf = new Intl.NumberFormat(FALLBACK_LOCALE, { maximumFractionDigits: 1, useGrouping: false });
  }
  NUMBER_FORMATS.set(locale, nf);
  return nf;
}

// The config's contribution to core's `fmtMeasurement`: the unit system to
// convert into, and a locale to render the digits with.
export function fmt(m: Measurement | null | undefined, rc: ResolvedConfig): string {
  if (!m) return "";
  const nf = numberFormat(rc.locale);
  return fmtMeasurement(convertMeasurement(m, rc.units), (n) => nf.format(n));
}

// The first targeted step shows its fill unsigned, every later pour carries a
// leading "+". Empty when `fmt` cannot render the amount — a lone "+" says nothing.
export function pourAmount(steps: readonly NormalizedStep[], index: number, rc: ResolvedConfig): string {
  const step = steps[index];
  if (!step || step.pourDelta === null) return "";
  const amount = fmt(step.pourDelta, rc);
  if (!amount) return "";
  return index === steps.findIndex((s) => s.toWater !== null) ? amount : `+${amount}`;
}
